[package]
name = "polkadot-statement-distribution"
version = "0.9.23"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Statement Distribution Subsystem"
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
polkadot-primitives = { path = "../../../primitives" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-state-access-benchmark" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
polkadot-node-subsystem = {path = "../../subsystem" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.8.1"
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
fatality = "0.0.6"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
futures-timer = "3.0.2"
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
