[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/zycon91/substrate", branch = "temp-relay" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/zycon91/substrate", default-features = false , branch = "temp-relay" }
sp-runtime = { git = "https://github.com/zycon91/substrate", branch = "temp-relay" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
