[package]
name = "pallet-xcm"
authors.workspace = true
edition.workspace = true
version.workspace = true


[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
log = { version = "0.4.17", default-features = false }

sp-std = { git = "https://github.com/CherryNetwork/substrate", default-features = false, branch = "upgrade-to-v0.9.34" }
sp-runtime = { git = "https://github.com/CherryNetwork/substrate", default-features = false, branch = "upgrade-to-v0.9.34" }
sp-core = { git = "https://github.com/CherryNetwork/substrate", default-features = false, branch = "upgrade-to-v0.9.34" }
frame-support = { git = "https://github.com/CherryNetwork/substrate", default-features = false, branch = "upgrade-to-v0.9.34" }
frame-system = { git = "https://github.com/CherryNetwork/substrate", default-features = false, branch = "upgrade-to-v0.9.34" }

xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/CherryNetwork/substrate", branch = "upgrade-to-v0.9.34" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
sp-io = { git = "https://github.com/CherryNetwork/substrate", default-features = false , branch = "upgrade-to-v0.9.34" }
xcm-builder = { path = "../xcm-builder" }
polkadot-parachain = { path = "../../parachain" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"xcm/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"frame-system/runtime-benchmarks"
]
try-runtime = ["frame-support/try-runtime"]
