[package]
name = "polkadot-client"
version = "0.9.33"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
frame-benchmarking = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
frame-benchmarking-cli = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
pallet-transaction-payment = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
frame-system = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
frame-system-rpc-runtime-api = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }

sp-consensus = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-storage = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-runtime = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-blockchain = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-api = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-core = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-keyring = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-inherents = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-timestamp = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-session = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-authority-discovery = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-finality-grandpa = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-consensus-babe = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-transaction-pool = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-block-builder = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-mmr-primitives = { git = "https://github.com/CherryNetwork/substrate", default-features = false , branch = "cherry-v0.9.33" }

sc-consensus = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sc-executor = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sc-client-api = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sc-service = { git = "https://github.com/CherryNetwork/substrate", default-features = false , branch = "cherry-v0.9.33" }

beefy-primitives = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }

# Polkadot Runtimes
cherry-runtime = { path = "../../runtime/cherry", optional = true }
rococo-runtime = { path = "../../runtime/rococo", optional = true }

polkadot-core-primitives = { path = "../../core-primitives" }
polkadot-primitives = { path = "../../primitives" }
polkadot-node-core-parachains-inherent = { path = "../core/parachains-inherent" }
polkadot-runtime-common = { path = "../../runtime/common" }

[features]
default = ["cherry"]
cherry = ["cherry-runtime"]
rococo = ["rococo-runtime"]
runtime-metrics = [
    "rococo-runtime/runtime-metrics",
    "cherry-runtime/runtime-metrics",
]
