[package]
name = "remote-ext-tests-bags-list"
version = "0.9.33"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
cherry-runtime = { path = "../../../runtime/cherry" }
cherry-runtime-constants = { path = "../../../runtime/cherry/constants" }

pallet-bags-list-remote-tests = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-tracing = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
frame-system = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }
sp-core = { git = "https://github.com/CherryNetwork/substrate", branch = "cherry-v0.9.33" }

clap = { version = "4.0.9", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.19.2", features = ["macros"] }
